on:
  push:
  schedule:
    - cron: '15 14 12 * *'

name: Continuous integration
env:
  RUSTC_WRAPPER: sccache
jobs:
  ci:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        experimental:
          - false
        rust:
          - stable
          - beta
          - 1.46.0  # Minimum supported Rust version
        include:
          - rust: nightly
            experimental: true

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install libegl1-mesa-dev
      - name: sccache cache files
        uses: actions/cache@v1.1.0
        with:
          path: /home/runner/.cache/sccache
          key: ${{ matrix.rust }}-sccache-${{ github.sha }}
          restore-keys: |
            ${{ matrix.rust }}-sccache
      - name: Download sccache
        run: |
          wget https://github.com/mozilla/sccache/releases/download/0.2.13/sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz
          tar -xvzf sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz
          sudo cp sccache-0.2.13-x86_64-unknown-linux-musl/sccache /usr/bin/sccache
          sccache --show-stats
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
